version: '3.3'
services:
  # DATABASES
  db:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'golangapp-backend'
      MYSQL_USER: 'golangapp'
      MYSQL_PASSWORD: 'golangapp123'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  my-db: