CREATE TABLE IF NOT EXISTS log_product(
    id INT NOT NULL AUTO_INCREMENT,
    status VARCHAR(255) NOT NULL,
    total_qty INT NOT NULL,
    total_price DECIMAL(9,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( id )
);